### YamlMime:Role
title: 功能顧問
metadata:
  title: 功能顧問
  description: 功能顧問會利用 Microsoft Dynamics 365 和 Microsoft Power Platform 來預測和規劃客戶的需求。
  ms.openlocfilehash: f227110263bb37e4001b7e625e7f2434f8f89994
  ms.sourcegitcommit: 9732383406c868d1279ca5ca79d423c5b99be073
  ms.translationtype: HT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 09/14/2021
  ms.locfileid: "132104644"
uid: role.functional-consultant
summary: >
  功能顧問會利用 Microsoft Dynamics 365 和 Microsoft Power Platform 來預測和規劃客戶的需求。
subTitle: 功能顧問會利用 Microsoft Dynamics 365 和 Microsoft Power Platform 來預測和規劃客戶的需求。
certificationPaths:
- title: Dynamics 365 Customer Service 功能顧問
  linkedInKeywords: Dynamics 365 Customer Service Functional Consultant
  uid: certification-path.d365-functional-consultant-customer-service
  prerequisites:
  - uid: certification.d365-fundamentals-customer-engagement-apps-crm
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-customer-service
    levels:
    - intermediate
- title: Dynamics 365 Field Service 功能顧問
  linkedInKeywords: Dynamics 365 Field Service Functional Consultant
  uid: certification-path.d365-functional-consultant-field-service
  prerequisites:
  - uid: certification.d365-fundamentals-customer-engagement-apps-crm
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-field-service
    levels:
    - intermediate
- title: Dynamics 365 財務功能顧問
  linkedInKeywords: Dynamics 365 Finance Functional Consultant
  uid: certification-path.d365-functional-consultant-financials
  prerequisites:
  - uid: certification.d365-fundamentals-finance-and-operations-apps-erp
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-financials
    levels:
    - intermediate
- title: Dynamics 365 製造功能顧問
  linkedInKeywords: Dynamics 365 Manufacturing Functional Consultant
  uid: certification-path.d365-functional-consultant-manufacturing
  prerequisites:
  - uid: certification.d365-fundamentals-finance-and-operations-apps-erp
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-manufacturing
    levels:
    - intermediate
- title: Dynamics 365 行銷功能顧問
  linkedInKeywords: Dynamics 365 Marketing Functional Consultant
  uid: certification-path.d365-functional-consultant-marketing
  prerequisites:
  - uid: certification.d365-fundamentals-customer-engagement-apps-crm
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-marketing
    levels:
    - intermediate
- title: Dynamics 365 銷售功能顧問
  linkedInKeywords: Dynamics 365 Sales Functional Consultant
  uid: certification-path.d365-functional-consultant-sales
  prerequisites:
  - uid: certification.d365-fundamentals-customer-engagement-apps-crm
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-sales
    levels:
    - intermediate
- title: Dynamics 365 供應鏈管理功能顧問
  linkedInKeywords: Dynamics 365 Supply Chain Management Functional Consultant
  uid: certification-path.d365-functional-consultant-supply-chain-management
  prerequisites:
  - uid: certification.d365-fundamentals-finance-and-operations-apps-erp
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-supply-chain-management
    levels:
    - intermediate
- title: Power Platform 的功能顧問
  linkedInKeywords: Power Platform Functional Consultant
  uid: certification-path.power-platform-functional-consultant-associate
  prerequisites:
  - uid: certification.d365-fundamentals-finance-and-operations-apps-erp
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-fundamentals-customer-engagement-apps-crm
    isOptional: true
    levels:
    - beginner
  - uid: certification.power-platform-functional-consultant-associate
    levels:
    - intermediate
- title: Dynamics 365 Business Central 功能顧問
  linkedInKeywords: Dynamics 365 Business Central Functional Consultant
  uid: certification-path.d365-business-central-functional-consultant-associate
  prerequisites:
  - uid: certification.d365-fundamentals-finance-and-operations-apps-erp
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-fundamentals-customer-engagement-apps-crm
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-business-central-functional-consultant-associate
    levels:
    - intermediate
certifications:
- uid: certification.d365-functional-consultant-customer-service
  requiredExams:
  - uid: exam.pl-200
  - uid: exam.mb-230
- uid: certification.d365-functional-consultant-field-service
  requiredExams:
  - uid: exam.pl-200
  - uid: exam.mb-240
- uid: certification.d365-functional-consultant-financials
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-310
- uid: certification.d365-functional-consultant-manufacturing
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-320
- uid: certification.d365-functional-consultant-marketing
  requiredExams:
  - uid: exam.pl-200
  - uid: exam.mb-220
- uid: certification.d365-functional-consultant-sales
  requiredExams:
  - uid: exam.pl-200
  - uid: exam.mb-210
- uid: certification.d365-functional-consultant-supply-chain-management
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-330
- uid: certification.power-platform-functional-consultant-associate
  requiredExams:
  - uid: exam.pl-200
- uid: certification.d365-business-central-functional-consultant-associate
  requiredExams:
  - uid: exam.mb-800
resources:
- title: Microsoft 訓練與認證指南
  description: 在簡短的訓練和認證指南中探索所有認證。
  href: https://aka.ms/TrainingCertDeck
- title: 訓練和認證海報
  description: 使用這個訓練和認證海報，選擇成功的途徑。
  href: https://aka.ms/traincertposter
- title: 認證的支援
  href: ../help.md
  description: 透過 Microsoft 認證支援論壇取得協助。 論壇仲裁者將會在星期一到星期五的一個工作天內回應。
