### YamlMime:Role
title: 解決方案架構設計師
metadata:
  title: 解決方案架構設計師
  description: 解決方案架構設計人員有計算、網路、儲存體、安全性等方面的專業知識。
  ms.openlocfilehash: 243a932c9851ea1979962b5d66a9e6e9e2cfa4cd
  ms.sourcegitcommit: 9732383406c868d1279ca5ca79d423c5b99be073
  ms.translationtype: HT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 09/14/2021
  ms.locfileid: "132104817"
uid: role.solution-architect
summary: >
  解決方案架構設計人員有計算、網路、儲存體、安全性等方面的專業知識。
subTitle: 解決方案架構設計人員有計算、網路、儲存體、安全性等方面的專業知識。
certificationPaths:
- title: Azure 解決方案架構師
  linkedInKeywords: Azure Solutions Architect
  uid: certification-path.azure-solutions-architect
  prerequisites:
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.azure-solutions-architect
    levels:
    - advanced
- title: Dynamics 365 財務和營運應用程式解決方案架構設計人員
  linkedInKeywords: Dynamics 365 Finance and Operations Apps Solution Architect
  uid: certification-path.d365-finance-and-operations-apps-solution-architect-expert
  prerequisites:
  - uid: certification.d365-fundamentals-customer-engagement-apps-crm
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-financials
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-manufacturing
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-supply-chain-management
    levels:
    - intermediate
  - uid: certification.d365-finance-and-operations-apps-developer-associate
    levels:
    - intermediate
  - uid: certification.d365-finance-and-operations-apps-solution-architect-expert
    levels:
    - advanced
- title: Power Platform 解決方案架構設計人員
  linkedInKeywords: Power Platform Solution Architect
  uid: certification-path.power-platform-solution-architect-expert
  prerequisites:
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-sales
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-marketing
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-customer-service
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-field-service
    levels:
    - intermediate
  - uid: certification.power-platform-functional-consultant-associate
    levels:
    - intermediate
  - uid: certification.power-platform-developer-associate
    levels:
    - intermediate
  - uid: certification.power-platform-solution-architect-expert
    levels:
    - advanced
certifications:
- uid: certification.azure-solutions-architect
  requiredExams:
  - uid: exam.az-303
  - uid: exam.az-304
- uid: certification.d365-finance-and-operations-apps-solution-architect-expert
  requiredExams:
  - uid: exam.mb-700
- uid: certification.azure-for-sap-workloads-specialty
  requiredExams:
  - uid: exam.az-120
- uid: certification.power-platform-solution-architect-expert
  requiredExams:
  - uid: exam.pl-600
resources:
- title: Microsoft 訓練與認證指南
  description: 在簡短的訓練和認證指南中探索所有認證。
  href: https://aka.ms/TrainingCertDeck
- title: 訓練和認證海報
  description: 使用這個訓練和認證海報，選擇成功的途徑。
  href: https://aka.ms/traincertposter
- title: 認證的支援
  href: ../help.md
  description: 透過 Microsoft 認證支援論壇取得協助。 論壇仲裁者將會在星期一到星期五的一個工作天內回應。
